### PR TITLE
Update grid system

### PR DESCRIPTION
**Pull request by eeeeenchanted**
The store now can receive an object as the `grid` value. If the user sets the item size, then upon resizing the item size would not change.

### CODE REVIEW

**Comment by flekschas** [comment]
I'll take a look, thanks! :) Can you provide an example of how to use the new grid object?

**Comment by eeeeenchanted** [comment]
The grid object has  6 properties: `itemSize`, `cols`, `rows`, `rowHeight`, `cellRatio`, and `itemPadding`(although I haven't implement item padding yet 😅) Users must set either `itemSize` or `cols`. If they set both,  the library will ignore `cols` property and just use `itemSize`. Other properties are not required.

An easy example would just be
```
pilingJS.set(grid, { cols: 10 });
```

**Comment by flekschas** [comment]
I looked over the code and introduced some minor changes. Most importantly, I flattened the grid options, so there is no property called `grid` anymore. Instead, the store now has `itemSize`, `columns`, `rows`, `rowHeight`, and `cellRatio`. This makes it a little bit easier to work with the options. Also, I added a sidebar to the website to allow a user to dynamically change grid options. 

I found out that updated the grid dynamically _doesn't_ cause a layout change. The store's properties are updated but the grid remains the same. As you see below only a window resize triggers a recalculation of the layout. Also, it seems like the grid isn't updated properly. (The number of columns doesn't match)

Jan-01-2020 17-24-00

Can you take a look at this?

**Comment by eeeeenchanted** [comment]
I added a function that updates the grid dynamically, but there is one problem: if I dispatch an action `movePiles` in the function, there will be an error `maximum call stack size exceeded`. I don't know why is that, can you help me look at the code?

**Comment by flekschas** [comment]
Thanks! That error message means that you introduced a loop. E.g., if `functionA` calls `functionB` which calls `functionA` you will get this error. The easiest way to find the loop is to put a logger into your new function and all other functions in the call trace. I will take a look but please try to narrow down the error. :)

**Comment by eeeeenchanted** [comment]
I just don't know where the loop is 😥If I change the `itemSize` from the sidebar, in the `update` function, I log out the `state.itemSize` and `newState.itemSize`, the former will always be the initial value, and the latter will be the new value, so the `initGrid` function will be called all the time. But I don't think the action `movePiles` has anything to do with the grid...

**Comment by flekschas** [comment]
Which function are you calling when the user resizes the browser window? That same function should be called I think.

**Comment by eeeeenchanted** [comment]
I added `itemPadding`, removed `rows` and fixed some bugs that appeared while resizing.

**Comment by eeeeenchanted** [comment]
I fixed #60 in this branch, since the grid system is different from the master branch.

**Pull request merged**
