### PR TITLE
Public event API

### PR DESCRIPTION
**Pull request by eeeeenchanted**
I added `init`, `render`, `pileSelect`, `pileFocus`, `pileActive`, `pileEnter` and `pileLeave` event API.

### CODE REVIEW

**Comment by flekschas** [comment]
Cool thanks I'll take a look in the next few days :)

**Comment by flekschas** [comment]
FYI, I cleaned up the code a bit and also added an event logger to the _lines_ example for testing.

**Comment by eeeeenchanted** [comment]
Ok, I edited DOCS, added new events and fixed the problems that events are repeatedly fired. 
Two things I'm not sure:
1. Dose `pileSelect` fires when the user clicks on a pile, and `pileFocus` fires when the user drags a pile?
2. When double click on a pile, the single click event would also fire, so `pileSelect` would fire twice when double-clicking, but it's not needed.

**Comment by flekschas** [comment]
Good question, maybe we should not fire the `pileSelect` event yet. As far as I remember we haven't implemented a select mode yet.

**Pull request merged**
